pyproject.toml: mute further mypy missing imports, show mypy's error codes
With this setting, mypy now outputs error code as well:

    $ mypy nmci/misc.py
    ...
    nmci/misc.py:8: error: Cannot find implementation or library stub for module named "systemd"  [import]

allowing to use more speficic comment to mute the error:

    from systemd import journal  # type: ignore [import]

instead of disabling mypy altogether for that statement with:

    # type: ignore

MR: https://gitlab.freedesktop.org/NetworkManager/NetworkManager-ci/-/merge_requests/1369