nmci/ctx: handle stderr messages for coredumpctl
      @crash ... passed in 0.207s
    Examing crash: /var/lib/systemd/coredump/core.NetworkManager.0.81142c387dc2491ca4a8f869a8571c22.56473.1656344501000000.lz4
    Traceback (most recent call last):
      File "features/environment.py", line 247, in after_scenario
        _after_scenario(context, scenario)
      File "features/environment.py", line 324, in _after_scenario
        nmci.ctx.check_coredump(context)
      File "/mnt/tests/NetworkManager-ci/nmci/ctx.py", line 647, in check_coredump
        f"echo backtrace | coredumpctl debug {pid}", shell=True
      File "/mnt/tests/NetworkManager-ci/nmci/process.py", line 173, in run_stdout
        context_hook=context_hook,
      File "/mnt/tests/NetworkManager-ci/nmci/process.py", line 106, in _run
        r_stderr.decode("utf-8", errors="replace"),
    Exception: `echo backtrace | coredumpctl debug 56473` printed something on stderr: Missing separate debuginfo for /usr/lib64/NetworkManager/1.32.10-5.el8_5/libnm-device-plugin-ovs.so
    Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/d6/59b95cdec06fa4c3d6f74e9a95e362dd75d554.debug
    Missing separate debuginfo for /usr/lib64/NetworkManager/1.32.10-5.el8_5/libnm-device-plugin-wifi.so
    Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/17/bb34563c2be87a52221fe271d7023e4c3a16cd.debug

    HOOK-ERROR in after_scenario: Exception: `echo backtrace | coredumpctl debug 56473` printed something on stderr: Missing separate debuginfo for /usr/lib64/NetworkManager/1.32.10-5.el8_5/libnm-device-plugin-ovs.so
    Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/d6/59b95cdec06fa4c3d6f74e9a95e362dd75d554.debug
    Missing separate debuginfo for /usr/lib64/NetworkManager/1.32.10-5.el8_5/libnm-device-plugin-wifi.so
    Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/17/bb34563c2be87a52221fe271d7023e4c3a16cd.debug

Redirect stderr to stdout to avoid the problem.